apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app-repo-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-app-repo-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/Tsuguya-HC"
        type: "git"
        githubAppID: "2998228"
        githubAppInstallationID: "157474973"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: privateKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-app-private-key
        property: private-key
        metadataPolicy: None
        nullBytePolicy: Ignore
