apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trading-pg-credentials
  namespace: database
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: trading-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: trading-pg-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
