apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flow
nameSuffix: -fast-review-muse
components:
  - ../../runtime/runc
  - ../../models/work/muse
  - ../../models/review/muse
  - ../../models/judge/claude
  - ../../models/filer/claude
